name: deploy to aws lambda

on: [push]

jobs:
  deploy_source:
    name: build and deploy lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version}}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version}} 
      - name: build and install
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true 
      - name: zip it
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r ./bundle.zip ./
      - name: deploy it
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws_secret_access_key:  ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws_region: ap-south-1
          function_name: reddit-api-reader
          zip_file: bundle.zip
           
 
